export type Refrigerator = { id: string; name: string; revision: number }
export type Device = { id: string; kind: string; label: string; created_at: string; last_seen_at: string | null; revoked_at: string | null; is_current: boolean }
export type ZoneGeometry = { x: number; y: number; width: number; height: number; layout_kind: 'vertical' | 'single_row' }
export type ZoneTemplate = { key: string; label: string; temperature_mode: 'cold' | 'frozen'; geometry: ZoneGeometry; layout_kind: 'vertical' | 'single_row'; adjustable_temperature: boolean; is_door: boolean }
export type Template = { key: string; name: string; zones: ZoneTemplate[] }
export type LayoutZone = { key: string; label: string; temperature_mode: 'cold' | 'frozen'; geometry: ZoneGeometry; slots: { id: string; key: string }[]; is_door: boolean }
export type Layout = { refrigerator_id: string; template_key: string; revision: number; zones: LayoutZone[] }
export type Category = { id: string; parent_id: string | null; name: string; icon_key: string | null; is_custom: boolean; display_order?: number }
export type InventoryBatch = { id: string; subcategory_id: string; subcategory_name: string; icon_key: string | null; storage_slot_id: string; item_name: string; quantity: number; production_date: string | null; best_before: string | null; product_description: string | null; barcode: string | null; expiry_status: string | null }
export type Icon = { key: string; label: string; asset_url: string; media_type?: 'image/svg+xml' | 'image/png' }
export type ExpirySettings = { ratio_percent: number; minimum_days: number; maximum_days: number }
export type NotificationSettings = { daily_reminder_enabled: boolean; reminder_time: string; device_health_enabled: boolean }
export type DueNotification = { kind: 'food' | 'device_health'; title: string; body: string }
export type RecognitionField = { value: string; confidence: number }
export type RecognitionOrderItem = { item_name: string; specification: string; quantity: number }
export type RecognitionResult = { kind: 'item' | 'order' | 'unknown'; fields: Record<string, RecognitionField>; order_items: RecognitionOrderItem[] }
export type BarcodeSuggestion = { item_name: string; subcategory_id: string; product_description: string | null; barcode: string }
export type ProductLookupResult = { found: boolean; item_name: string | null; product_description: string | null; barcode: string; source: string | null }
export type QrLookupResult = { kind: 'item' | 'url' | 'text' | 'unknown'; payload: string; fields: Record<string, RecognitionField> }
export type IconCandidate = { id: string; asset_url: string }
export type IconGeneration = { id: string; candidates: IconCandidate[] }
export type RecipeIngredient = { subcategory_name: string; quantity: number }
export type RecipeEntry = { id: string; weekday: number; dish_name: string; note: string | null; completed: boolean; ingredients: RecipeIngredient[]; missing: RecipeIngredient[] }
export type RecipeDay = { weekday: number; label: string; entries: RecipeEntry[] }
export type RestockEntry = { weekday: number; label: string; dish_name: string; missing: RecipeIngredient[] }
export type RecipeHistoryWeek = { week_start: string; label: string; recipe_count: number; preview: string }
