// @ts-expect-error The frontend build intentionally omits Node types; this is a test-only source contract.
import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

const androidPlugin = readFileSync(
  new URL('../android/app/src/main/java/com/fridgeboard/app/NativeCapabilitiesPlugin.java', import.meta.url),
  'utf8',
)
const manifest = readFileSync(new URL('../android/app/src/main/AndroidManifest.xml', import.meta.url), 'utf8')
const filePaths = readFileSync(new URL('../android/app/src/main/res/xml/file_paths.xml', import.meta.url), 'utf8')
const iosInfo = readFileSync(new URL('../ios/App/App/Info.plist', import.meta.url), 'utf8')
const sceneDelegate = readFileSync(new URL('../ios/App/App/SceneDelegate.swift', import.meta.url), 'utf8')
const iosPlugin = readFileSync(new URL('../ios/App/App/NativeCapabilitiesPlugin.swift', import.meta.url), 'utf8')

describe('P13.5 原生能力桥', () => {
  it('Android 注册系统返回、分享和网络状态能力', () => {
    expect(androidPlugin).toContain('@CapacitorPlugin(name = "NativeCapabilities")')
    expect(androidPlugin).toContain('notifyListeners("backButton"')
    expect(androidPlugin).toContain('Intent.ACTION_SEND')
    expect(androidPlugin).toContain('text + "\\n" + url')
    expect(androidPlugin).toContain('registerDefaultNetworkCallback')
    expect(androidPlugin).toContain('backCallback.remove()')
    expect(androidPlugin).toContain('@ActivityCallback')
    expect(androidPlugin).toContain('shareCompleted')
    expect(androidPlugin).toContain('openExternalUrl')
    expect(androidPlugin).toContain('CustomTabsClient.getPackageName')
    expect(androidPlugin).toContain('CustomTabsIntent.Builder')
    expect(androidPlugin).toContain('getAppInfo')
    expect(androidPlugin).toContain('canInstallUnknownApps')
    expect(androidPlugin).toContain('hasUnknownSourcesPermission')
    expect(androidPlugin).toContain('handleOnResume')
    expect(androidPlugin).toContain('notifyListeners("appResume"')
    expect(androidPlugin).toContain('setSystemBars')
    expect(androidPlugin).toContain('setStatusBarColor(color)')
    expect(androidPlugin).toContain('setNavigationBarColor(color)')
    expect(androidPlugin).toContain('getWebView().setBackgroundColor(color)')
    expect(androidPlugin).toContain('setAppearanceLightStatusBars')
    expect(androidPlugin).toContain('setAppearanceLightNavigationBars')
    expect(androidPlugin).toContain('pickImage')
    expect(androidPlugin).toContain('PICK_IMAGES')
    expect(androidPlugin).toContain('Intent.ACTION_PICK')
    expect(androidPlugin).toContain('MediaStore.Images.Media.EXTERNAL_CONTENT_URI')
    expect(androidPlugin).toContain('ACTION_OPEN_DOCUMENT')
    expect(androidPlugin).toContain('IMAGE_PICK_CANCELLED')
    expect(androidPlugin).toContain('MAX_ICON_BYTES')
    expect(androidPlugin).toContain('updateExecutor.execute(() -> readPickedImage')
    expect(androidPlugin).toContain('image/png", "image/jpeg", "image/webp"')
    expect(androidPlugin).toContain('Bitmap.CompressFormat.PNG')
    expect(androidPlugin).toContain('inJustDecodeBounds = true')
    expect(androidPlugin).toContain('MAX_ICON_PIXELS')
    expect(androidPlugin).toContain('MAX_ICON_PIXELS = 16_000_000L')
    expect(androidPlugin).not.toContain('16L * 1024L * 1024L')
    expect(androidPlugin).toContain('downloadAndInstallApk')
    expect(androidPlugin).toContain('MessageDigest')
    expect(androidPlugin).toContain('ACTION_INSTALL_PACKAGE')
    expect(androidPlugin).toContain('EXTRA_RETURN_RESULT')
    expect(androidPlugin).toContain('EXTRA_STATUS_MESSAGE')
    expect(androidPlugin).toContain('apkInstallCompleted')
    expect(androidPlugin).toContain('APK_INSTALL_SIGNATURE_MISMATCH')
    expect(androidPlugin).toContain('当前应用与更新包签名不一致')
    expect(androidPlugin).toContain('UNKNOWN_SOURCES_DISABLED')
    expect(manifest).toContain('android.permission.REQUEST_INSTALL_PACKAGES')
    expect(filePaths).toContain('<external-files-path name="apk_updates" path="updates/" />')
    expect(androidPlugin).toContain('github.com')
    expect(androidPlugin).toContain('release-assets.githubusercontent.com')
    expect(androidPlugin).not.toContain('app.flycn.fyi')
    expect(androidPlugin).not.toContain('com.android.chrome')
    expect(manifest).toContain('android:enableOnBackInvokedCallback="true"')
    expect(manifest).toContain('android.permission.ACCESS_NETWORK_STATE')
  })

  it('Debug 构建在存在共享 keystore 时复用 Release 签名', () => {
    const buildGradle = readFileSync(new URL('../android/app/build.gradle', import.meta.url), 'utf8')
    expect(buildGradle).toContain('sharedSigningAvailable')
    expect(buildGradle).toContain('if (sharedSigningAvailable) signingConfig signingConfigs.release')
  })

  it('Android 与 iOS 原生 App 仅支持正向竖屏', () => {
    expect(manifest).toContain('android:screenOrientation="portrait"')
    expect(iosInfo).toContain('<key>UIRequiresFullScreen</key>')
    expect(iosInfo).toContain('<key>UISupportedInterfaceOrientations</key>')
    expect(iosInfo).toContain('<key>UISupportedInterfaceOrientations~ipad</key>')
    expect(iosInfo).not.toContain('UIInterfaceOrientationLandscapeLeft')
    expect(iosInfo).not.toContain('UIInterfaceOrientationLandscapeRight')
    expect(iosInfo).not.toContain('UIInterfaceOrientationPortraitUpsideDown')
  })

  it('iOS 使用原生边缘手势桥接 React 返回，并关闭 WebView history 手势', () => {
    expect(sceneDelegate).toContain('allowsBackForwardNavigationGestures = false')
    expect(sceneDelegate).toContain('NativeCapabilitiesPlugin()')
    expect(iosPlugin).toContain('UIScreenEdgePanGestureRecognizer')
    expect(iosPlugin).toContain('gesture.cancelsTouchesInView = false')
    expect(iosPlugin).toContain('gestureRecognizerShouldBegin')
    expect(iosPlugin).toContain('completionWithItemsHandler')
    expect(iosPlugin).toContain('openExternalUrl')
    expect(iosPlugin).toContain('UIApplication.shared.open')
    expect(iosPlugin).toContain('CAPPluginMethod(name: "getAppInfo"')
    expect(iosPlugin).toContain('CFBundleShortVersionString')
    expect(iosPlugin).toContain('CFBundleVersion')
    expect(iosPlugin).toContain('DispatchQueue.main.async')
    expect(iosPlugin).toContain('notifyListeners("backButton"')
    expect(iosPlugin).toContain('PHPickerViewController')
    expect(iosPlugin).toContain('UIDocumentPickerViewController')
    expect(iosPlugin).toContain('pickImage')
    expect(iosPlugin).toContain('pendingImageCall?.reject("已取消图片选择", "IMAGE_PICK_CANCELLED")')
    expect(iosPlugin).toContain('startAccessingSecurityScopedResource')
    expect(iosPlugin).toContain('DispatchQueue.global(qos: .userInitiated)')
    expect(iosPlugin).toContain('10_000_000')
    expect(iosPlugin).toContain('image/png", "image/jpeg", "image/webp"')
    expect(iosPlugin).toContain('convertHEICToPNG')
    expect(iosPlugin).toContain('pngData()')
    expect(iosPlugin).toContain('CGImageSourceCreateWithData')
    expect(iosPlugin).toContain('kCGImagePropertyPixelWidth')
    expect(iosPlugin).toContain('Int64(width) * Int64(height) <= 16_000_000')
    expect(iosPlugin).not.toContain('16 * 1024 * 1024')
    const pickerBody = iosPlugin.slice(iosPlugin.indexOf('loadDataRepresentation'), iosPlugin.indexOf('public func documentPicker'))
    expect(pickerBody.indexOf('data.count <= 10_000_000')).toBeGreaterThanOrEqual(0)
    expect(pickerBody.indexOf('data.count <= 10_000_000')).toBeLessThan(pickerBody.indexOf('convertHEICToPNG'))
  })

  it('原生 HEIC 像素契约使用十进制 16MP，刚超边界必须拒绝', () => {
    const maxPixels = 16_000_000
    expect(4_000 * 4_000).toBe(maxPixels)
    expect(4_001 * 4_000).toBeGreaterThan(maxPixels)
    expect(androidPlugin).toContain('pixels > MAX_ICON_PIXELS')
    expect(iosPlugin).toContain('<= 16_000_000')
  })
})
